INSERT INTO reservation_system.airport (name, city) VALUES ('AMS', 'Amsterdam');
INSERT INTO reservation_system.airport (name, city) VALUES ('CAN', 'Guangzhou');
INSERT INTO reservation_system.airport (name, city) VALUES ('CDG', 'Paris');
INSERT INTO reservation_system.airport (name, city) VALUES ('CIT', 'Shymkent');
INSERT INTO reservation_system.airport (name, city) VALUES ('DXB', 'Dubai');
INSERT INTO reservation_system.airport (name, city) VALUES ('FRA', 'Frankfurt');
INSERT INTO reservation_system.airport (name, city) VALUES ('HCO', 'Hangzhou');
INSERT INTO reservation_system.airport (name, city) VALUES ('HKG', 'Hong Kong');
INSERT INTO reservation_system.airport (name, city) VALUES ('JFK', 'New York');
INSERT INTO reservation_system.airport (name, city) VALUES ('LAX', 'Los Angeles');
INSERT INTO reservation_system.airport (name, city) VALUES ('LHR', 'London');
INSERT INTO reservation_system.airport (name, city) VALUES ('ORD', 'Chicago');
INSERT INTO reservation_system.airport (name, city) VALUES ('PEK', 'Beijing');
INSERT INTO reservation_system.airport (name, city) VALUES ('PVG', 'Shanghai');
INSERT INTO reservation_system.airport (name, city) VALUES ('SIN', 'Singapore');
