INSERT INTO reservation_system.airplane (id, seats, airline_name) VALUES (1, 100, 'China Southern');
INSERT INTO reservation_system.airplane (id, seats, airline_name) VALUES (2, 58, 'China Southern');
INSERT INTO reservation_system.airplane (id, seats, airline_name) VALUES (69, 1, 'China Southern');
INSERT INTO reservation_system.airplane (id, seats, airline_name) VALUES (1234, 222, 'China Southern');
INSERT INTO reservation_system.airplane (id, seats, airline_name) VALUES (11111, 200, 'Delta');
INSERT INTO reservation_system.airplane (id, seats, airline_name) VALUES (22222, 100, 'Delta');
INSERT INTO reservation_system.airplane (id, seats, airline_name) VALUES (89098, 120, 'China Southern');
INSERT INTO reservation_system.airplane (id, seats, airline_name) VALUES (122344, 123, 'China Southern');
INSERT INTO reservation_system.airplane (id, seats, airline_name) VALUES (123300, 450, 'China Southern');
INSERT INTO reservation_system.airplane (id, seats, airline_name) VALUES (123344, 35, 'China Southern');
INSERT INTO reservation_system.airplane (id, seats, airline_name) VALUES (170982, 50, 'China Southern');
INSERT INTO reservation_system.airplane (id, seats, airline_name) VALUES (690690, 120, 'China Southern');
INSERT INTO reservation_system.airplane (id, seats, airline_name) VALUES (699999, 2, 'China Southern');
INSERT INTO reservation_system.airplane (id, seats, airline_name) VALUES (1223445, 340, 'China Southern');
INSERT INTO reservation_system.airplane (id, seats, airline_name) VALUES (2122234, 120, 'China Southern');
