version: "3"
services:
# THIS IS STILL IN PROGRESS
  app:
    build: .
    container_name: airline-ticket-system
    ports:
      - 8000:8000
    environment:
      MYSQLHOST: mysqldb
      MYSQLUSER: root
      MYSQLPASSWORD: root
      MYSQLDATABASE: airline
    depends_on:
      - mysqldb
    volumes:
      - .:/app

  mysql:
    image: mysql:8.0.32
    ports:
      - "127.0.0.1:3306:3306"
    env_file:
      - .env
    volumes:
      - "sql_data:/var/lib/mysql"
      - "sql_log:/var/log/mysql"
    networks:
      - default
volumes:
  sql_data:
    driver: local
  sql_log:
    driver: local

networks:
  default:
    driver: bridge


# THIS IS ADDITIONAL PART
  mysqldb:
    image: mysql:8.0.33
    restart: always
    ports:
      - 9999:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airline
    volumes:
      - ./airline/init_db:/docker-entrypoint-initdb.d